# Generated by Django 3.1.3 on 2020-11-29 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherapi',
            name='period',
        ),
        migrations.AddField(
            model_name='weatherapi',
            name='from_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weatherapi',
            name='to_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
