# Generated by Django 3.1.3 on 2020-11-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20201129_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherapi',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='from_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='to_time',
            field=models.TimeField(),
        ),
    ]
